### ISSUE TITLE
platform.linux_distribution() has been deprecated since python 3.5

### ISSUE THREAD

**Issue by arin17bishwa** [rugglcon/python-backgroundchanger#21]
platform.linux_distribution() has been deprecated, leading to an error in newer python versions.

> ValueError: Linux is not yet implemented to change the background. However, you can still change the background. photo name: /home/bishwajit/.config/python-backgroundchanger/photos/f7Af8eeQue0.png

**Comment by zeborg** [comment]
Apparently that can still be fixed by implementing the "distro" module instead of "platform".
@arin17bishwa if you don't mind, shall I make the PR?

**Comment by arin17bishwa** [comment]
Actually I have already resolved it in this [commit](https://github.com/rugglcon/python-backgroundchanger/pull/22/commits/d2f98305a4f43ecd1b6d53aa679a1a9b1b79d193).
Actually I created the issue before finishing my work on my PR. Really sorry for the confusion.
Should this issue remain open until my PR gets merged?

**Comment by conruggles** [comment]
Resolved in #22
